### ISSUE TITLE
About wrappers

### ISSUE THREAD

**Issue by rokoroku** [open-korean-text/open-korean-text#10]
안녕하세요, 저는 [node-twitter-korean-text](https://github.com/rokoroku/node-twitter-korean-text) 를 maintain하고 있었습니다만, 이번 open-korean-text으로의 변경에 맞추어 어떤 방향으로 업데이트를 진행하여야 좋을지 문의드립니다.

1. 기존 repository [node-twitter-korean-text](https://github.com/rokoroku/node-twitter-korean-text)  이용 (node-open-korean-text로 이름 변경)
2. fork된 repository [open-korean-text-wrapper-node-2](https://github.com/openkoreantext/open-korean-text-wrapper-node-2) 이용 

2의 경우는 권한이 부여되지 않아 작업이 불가능합니다만, 
커뮤니티에 도움이 되는 방향으로 결정해 주시면 그에 맞춰 따라가도록 하겠습니다. :)

EDIT: 2의 방향이라면, openkoreantext라는 일반 계정보다는 Github Organizaiton을 생성하는 방향은 어떨까요?

**Comment by nlpenguin** [comment]
아 질문 감사드립니다. Organization을 하면 한달에 $25 이상이라 너무 비싼 것 같아서요. 일단은 모든 저자 분들을 collaborator로 초대해 드릴게요. Fork에서 하는 것이 한 곳에 모여져 있어서 좋을 것 같기는 합니다. 감사합니다!!

**Comment by rokoroku** [comment]
`Unlimited members and public repositories for free.`

Public repositories만 사용하는 organization은 무료 아닌가요? ^^;
아무튼 권한을 주시면 그에 맞춰 업데이트를 진행할텐데, npm 레지스트리 이름이 `open-korean-text-wrapper-node-2`는 너무 긴 것 같기도 해서 `node-open-korean-text`로 등록하는 방향으로 진행해 볼게요.

**Comment by openkoreantext** [comment]
아 무료네요! 네 그런데 일관성있는 이름을 쓰려고 노력중인데요, open-korean-text-node는 어떨까요?

**Comment by openkoreantext** [comment]
말씀하신대로 organization 만들었습니다.

**Comment by rokoroku** [comment]
네 `open-korean-text-node`로 진행하겠습니다! :)

**Comment by nlpenguin** [comment]
Admin으로 초대장 보내드렸습니다.
