### ISSUE TITLE
Question related to nouns dictionary size

### ISSUE THREAD

**Issue by Ka1wa** [open-korean-text/open-korean-text#12]
Hello! First of all big thanks for continuing the twitter-korean-text project. I'm excited to see what's next :)

I am currently comparing two Korean text analyzers, which are open-korean-text and mecab-ko. One of the biggest advantages of open-korean-text are the offset and length variables, especially in combination with stemming and the offset/length staying identical to the original string. My use case requires a reconstruction of the text at a later stage, which these values make possible.

My questions is however related to the dictionary size of the nouns. The mecab-ko dictionary currently has over 200.000 nouns while open-korean-text is floating at 30.000. Is there something keeping me from simply importing all the nouns from mecab-ko into open-korean-text aside from a potential performance hit?

I'd like to contribute to this project in the future, but as a Korean learner I'm afraid I can't really contribute much in the actual analyzing of the language, the dictionary however I can do. I'd like to use the project for a Korean learning hobby project which would require up-to-date celebrity names, game character names etc.

Thanks again and I hope to hear from you!

**Comment by nlpenguin** [comment]
Hi Ka1wa,

Thanks for your interest in open-korean-text! There is no reason we cannot include mecab-ko dictionary. Can you send the dictionary to me so that I can add them to the dictionary? As a matter of fact, I hand-created all the dictionaries in open-korean-text so there is a huge room to improve.

**Comment by Ka1wa** [comment]
The dictionary is available on bitbucket here: https://bitbucket.org/eunjeon/mecab-ko-dic/downloads

Once you download one of the dictionaries (most recent one 09/2015), there's a bunch of CSV files in the archive with the following names: https://docs.google.com/spreadsheets/d/1-9blXKjtjeKZqsf4NzHeYJCrr49-nXeRF6D80udfcwY/edit#gid=589544265

The structure of the dictionary is slightly different but I think it should be possible to simply take the first comma seperated value and add it to your list.

**Comment by nearbydelta** [comment]
Maybe this document will be helpful for matching morpheme types, which I organized about a year ago: [Koala NLP 1.0 태그 분류표](https://docs.google.com/spreadsheets/d/1OGM4JDdLk6URuegFKXg1huuKWynhg_EQnZYgTmG4h0s/edit#gid=1058860532). This is a comparison sheet on morpheme types, for well-known Korean POS taggers.

I think NNG, NNB, NNBC and NP (of Mecab) can be Nouns (of OpenKoreanText),
and NNP can be a ProperNoun (of OpenKoreanText).

By the way, is it sufficient for other morpheme types? For example, like modifiers(Determiner of OpenKoreanText).

**Comment by nlpenguin** [comment]
We will need some careful manual work to add the dictionaries as the "nouns" in mecab-ko-dic are not 100% nouns. I will take a closer look.

**Comment by nlpenguin** [comment]
Oh, I checked again and realized that we already have 262,2018 nouns. `noun.txt` only contains common nouns, and there are so many other noun dictionary files listed below. 

@Ka1wa Thank you for reporting. I will close the issue.

```
~/workspace/open-korean-text/open-korean-text/src/main/resources/org/openkoreantext/processor/util/noun master 🐶  wc *               5:08:02
     203     251    2039 bible.txt
     155     188    1631 company_names.txt
    2649    3346   26494 congress.txt
    9728   12436  108142 entities.txt
    1006    1268   10366 foreign.txt
     519     617    5423 geolocations.txt
     559     686    5371 kpop.txt
     143     172    1337 lol.txt
      96     116     876 names.txt
   26508   31660  219537 nouns.txt
     161     210    1781 pokemon.txt
      65      76     569 profane.txt
     174     208    1521 slangs.txt
      19      24     202 spam.txt
      32      35     254 twitter.txt
  158521  210725 1972156 wikipedia_title_nouns.txt
  200538  262018 2357699 total
```
