### ISSUE TITLE
 분석기 사용방법 문의

### ISSUE THREAD

**Issue by juneng603** [open-korean-text/open-korean-text#15]
@nlpenguin 

안녕하세요. ES에서 open-korean-text를 도입하여 사용중에 있습니다.
(ES : 2.4.x, open-korean-text: 1.1)

사용도중에 질문이 있어 게시글 남겨봅니다. 
(google group에서는 글남기기 권한이 필요한지.. 글을 남길 수가 없어 여기에 먼저 남깁니다. 추후에 옮길 수 있을때 옮기도록 하겠습니다.)

질의 "닭도리탕" 이고
분석결과는
```
{
   "tokens": [
      {
         "token": "닭도리탕",
         "start_offset": 0,
         "end_offset": 4,
         "type": "Noun",
         "position": 0
      }
   ]
}
```
로 분석이 됩니다. 

닭도리탕은 합성어로 "닭"과 "도리탕"을 합쳐놓은 것입니다.
분석결과에서 "닭/도리/탕/도리탕/닭도리탕"을 함께 보고 싶은데요. (비록 닭볶음탕으로 이야기하는것이 옳을지라도...)
물론 두 단어 모두 사전에는 포함되어있습니다.

방법이 있을까요?

**Comment by nlpenguin** [comment]
안타깝지만 지금으로서는 방법이 없습니다. 다만 간단한 수정을 통해 top n parsing을 return하도록 할 수는 있을 것 같습니다.

**Comment by juneng603** [comment]
아 네~ 어느쪽을 수정하면 되는지 말씀주시면 제가 테스트 진행해보겠습니다. :0

**Comment by nlpenguin** [comment]
https://github.com/open-korean-text/open-korean-text/blob/master/src/main/scala/org/openkoreantext/processor/tokenizer/KoreanTokenizer.scala#L200 이 부분에서 최종 하나만 선정하게 되어 있습니다. 그런데 여러개를 return하려면 method signature도 바꿔야 할 것 같습니다.

**Comment by juneng603** [comment]
@nlpenguin 오호 :0 감사합니다!! 이와 같은 처리를 configurable하게 사용자가 선택할 수 있게 하면 더 좋겠네요!.
