### ISSUE TITLE
#extractPhrases 동작 오류

### ISSUE THREAD

**Issue by keepcosmos** [open-korean-text/open-korean-text#19]
```
val tokens: Seq[KoreanToken] = OpenKoreanTextProcessor.tokenize(normalized)
println(tokens)
// List(한국어(Noun: 0, 3), 를(Josa: 3, 1),  (Space: 4, 1), 처리(Noun: 5, 2), 하는(Verb: 7, 2),  (Space: 9, 1), 예시(Noun: 10, 2), 입니(Adjective: 12, 2), 다(Eomi: 14, 1), ㅋㅋ(KoreanParticle: 15, 2),  (Space: 17, 1), #한국어(Hashtag: 18, 4))

// Phrase extraction
val phrases: Seq[KoreanPhrase] = OpenKoreanTextProcessor.extractPhrases(tokens, filterSpam = true, enableHashtags = true)
println(phrases)
```
위의 구문을 수행할 경우,

* 예상
```
// List(한국어(Noun: 0, 3), 처리(Noun: 5, 2), 처리하는 예시(Noun: 5, 7), 예시(Noun: 10, 2), #한국어(Hashtag: 18, 4))
```

* 실제
```
/// List(한국어(Noun: 0, 3), 예시(Noun: 10, 2), #한국어(Hashtag: 18, 4))
```

v1.1를 사용해서 `#extractPhrases` 를 수행하면 메뉴얼에 작성된 예시와 다른 결과가 나옵니다. 무엇이 제대로 된 결과인지 알 수 있을까요?

**Comment by MechanicKim** [comment]
최근 PR(Added tokenizeTopN #17)을 통과하면서 tokenizeTopN 추가 작업이 있었는데요.
어구 추출을 위해 토큰 화가 먼저 이루어져야 하기에 결과에도 변화가 있으리라고 보여지는데요.
Readme 문서의 수정이 이루어져야 할 것으로 보입니다.

@nlpenguin Help us to get an answer! :-)

**Comment by keepcosmos** [comment]
@MechanicKim Readme가 수정되어야한다는건, 

`List(한국어(Noun: 0, 3), 예시(Noun: 10, 2), #한국어(Hashtag: 18, 4))` 결과가 적합하단 뜻인가요?

**Comment by MechanicKim** [comment]
@keepcosmos 최근 PR의 토큰화 부분에서 변화를 살펴보고 생각해본지라 저는 말씀하신 결과가 적합하다고 판단했습니다. 정확한 답은 @nlpenguin 님께서 해주실 수 있을거라 생각합니다.

**Comment by keepcosmos** [comment]
@MechanicKim 네~ 감사합니다. 👍

**Comment by nlpenguin** [comment]
답장이 늦어 죄송합니다. 사전 업데이트 후에 "처리하는" 이 "처리 + 하다"에서 "처리하는"이라는 동사로 인식되면서 그렇게 된 것 같습니다. 원래대로 인식되도록 수정해야 할 것 같습니다.

**Comment by nlpenguin** [comment]
새 버전 2.0.1을 릴리즈하였습니다.

**Comment by keepcosmos** [comment]
@nlpenguin  감사합니다 ❤️ mvn repository에 릴리즈 됐는지 확인 부탁드려요.

**Comment by nlpenguin** [comment]
@keepcosmos 엇 혹시 안 되었나요? 금요일 저녁에 릴리즈 했습니다..

**Comment by MechanicKim** [comment]
아직 릴리즈가 안되었네요. ^^;
<img width="690" alt="2017-05-08 9 02 00" src="https://cloud.githubusercontent.com/assets/12149783/25786284/2782b66a-33cd-11e7-961d-421388d54ae8.png">

**Comment by nlpenguin** [comment]
아 이름이 바뀌었어요... http://mvnrepository.com/artifact/org.openkoreantext/open-korean-text

**Comment by keepcosmos** [comment]
확인하였습니다. 감사합니다. 🎉
