### ISSUE TITLE
'~라면서' 처리 오류

### ISSUE THREAD

**Issue by nearbydelta** [open-korean-text/open-korean-text#26]
OpenKoreanTokenizer 업데이트에 맞춰서 다른 라이브러리를 업데이트하고 테스트하던 중에 다음과 같은 오류를 발견했습니다.

테스트 문장은 다음과 같습니다.
```txt
이들은 "현역 국회의원인 시점에 자서전을 내면서 부끄러운 범죄 사실을 버젓이 써 놓고 사과 한마디 없다는 것은 더 기막히다"라면서 "대선 후보가 아닌 정상적인 사고를 가진 한 인간으로서도 자질 부족인 홍 후보의 사퇴를 촉구한다"고 밝혔다.
```

여기서 문제가 되는 구조는 ``` "~"라면서 ``` 부분입니다.
openkoreantext.org에서도 테스트했을 때 다음과 같이 통과합니다.

*성공*
 - 그는 "ABCD"라고 말을 외쳤다
 - 그는 "ABCD"라는 말을 외쳤다

*실패*
 - 그는 "ABCD"라면서 말을 외쳤다.
 - 그는 "ABCD"라면서도 말을 외쳤다.

1.3 버전까지는 테스트에서 이상이 없었는데, 2.0.3에서 이렇게 되었습니다.
사전에는 '어미' 항목으로 있는데 왜 이럴까요?

**Comment by nearbydelta** [comment]
비슷한 문제로 다음 문장 구조도 있습니다.

* A의 B를 놓고 C가 벌어진 점
이 경우에는 '놓고'가 tokenize 과정에서 누락됩니다.

**Comment by nlpenguin** [comment]
버그 보고 감사합니다. 수정하겠습니다~!
