### ISSUE TITLE
Improve coverall coverage

### ISSUE THREAD

**Issue by nlpenguin** [open-korean-text/open-korean-text#30]
https://coveralls.io/github/open-korean-text/open-korean-text?branch=master

We are at 98% in test coverage. Let's make it 100%.

...koreantext/processor/tokenizer/KoreanChunker.scala - @MechanicKim 
...reantext/processor/tokenizer/KoreanTokenizer.scala - @HewonJeong 
...enkoreantext/processor/stemmer/KoreanStemmer.scala - @ovekyc 
.../org/openkoreantext/processor/util/KoreanPos.scala - @KyuaKwon 
...text/processor/util/KoreanDictionaryProvider.scala - @HewonJeong 
...antext/processor/normalizer/KoreanNormalizer.scala - @ovekyc 
...essor/phrase_extractor/KoreanPhraseExtractor.scala - @KyuaKwon 

Sample PR: https://github.com/open-korean-text/open-korean-text/pull/28

질문 있으면 댓글로 달아주세요.

**Comment by nlpenguin** [comment]
7/2까지 PR올려주세요. 물론 Hard deadline은 아닙니다. 그리고 궁금한 거 있으면 혼자 머리 싸매지 말고 바로 질문 주세요.

**Comment by nlpenguin** [comment]
설치하고 개발하는 기본 셋팅 안내:
https://github.com/open-korean-text/open-korean-text/blob/master/docs/contribution-guide.md

**Comment by nlpenguin** [comment]
@MechanicKim Hmm I found scoverall is broken now. I am fixing it.

**Comment by MechanicKim** [comment]
@nlpenguin Okay! I got it.
Is there anything I can help you with?

**Comment by nlpenguin** [comment]
https://coveralls.io/github/open-korean-text/open-korean-text?branch=master

업데이트 해서 최신 데이터를 보니 더 떨어졌다는 ㅠㅜ

@MechanicKim 새로운 리포트 기반해서 일을 다시 나눠 주세요. 고마워요~!

**Comment by heartjigi** [comment]
저도 일감을 나눠주실 수 있을까요 ?
@nlpenguin @MechanicKim

**Comment by ovekyc** [comment]
Assign job to dabin. lol
...antext/processor/normalizer/KoreanNormalizer.scala - @heartjigi

**Comment by nlpenguin** [comment]
여러분 데드라인이 다가옵니다. 이 데드라인이 지나면 아무 일도 생기지 않습니다. 하고 싶을 때 여유롭게 하세요. ㅋㅋ 못할 것 같으면 얘기해 주시고요, 설치나 수정하는 방법에 질문이 있으면 @MechanicKim 이나 저에게 질문 주세요.

**Comment by SarahhhC** [comment]
Please assign me too! 😆 @nlpenguin @MechanicKim

**Comment by MechanicKim** [comment]
Assign job to @SarahhhC .
.../org/openkoreantext/processor/util/KoreanPos.scala - @SarahhhC 

Thanks, @KyuaKwon 👍

**Comment by ksseono** [comment]
@nlpenguin 데드라인이라 하심은.. 뭔가 평가 같은 것이 있는건가요? 제가 잘 몰라서 ^^; 저도 도움드릴 수 있는 부분이 있을까요?

**Comment by MechanicKim** [comment]
This issue has not been solved yet!

**Comment by MechanicKim** [comment]
@ksseono 이 이슈는 아직 끝난게 아니랍니다 ^^
평가 같은 건 아니고 code coverage를 높이기 위한 프로젝트로
현재 계속 진행 중에 있답니다. :-)

**Comment by ksseono** [comment]
@MechanicKim 헉 제가 실수로 close를 눌렀었군요.. 죄송합니다 ^^;;;

**Comment by nlpenguin** [comment]
@ksseono 아 그냥 장난으로 데드라인을 정하고 했었는데요 100%가 될 때까지 천천히 하는 프로젝트입니다. 언제든지 도와주세요! @MechanicKim 파일 assign 부탁드려요.

**Comment by nlpenguin** [comment]
@ksseono https://coveralls.io/github/open-korean-text/open-korean-text?branch=master

여기에 보면 ₩...koreantext/processor/OpenKoreanTextProcessor.scala₩ 이 파일이 90%인데요, 테스트 하나 추가하면 100%가 됩니다. 테스트 추가 부탁드려요.

**Comment by nlpenguin** [comment]
90.0		...koreantext/processor/OpenKoreanTextProcessor.scala	149	10	9	1	1.0
94.2		...reantext/processor/tokenizer/KoreanTokenizer.scala	254	69	65	4	1.0
97.35		...essor/phrase_extractor/KoreanPhraseExtractor.scala	338	113	110	3	1.0
97.56		...text/processor/util/KoreanDictionaryProvider.scala	172	41	40	1	1.0
97.56		.../org/openkoreantext/processor/util/KoreanPos.scala	155	41	40	1	1.0

이제는 딱 10군데 남았습니다. 모두모두 감사드려요~!! Keep up the great work!

**Comment by MechanicKim** [comment]
엇! 제가 한 발 늦었네요.

**Comment by ksseono** [comment]
@nlpenguin 알겠습니다. 그런데 아직 제가 TokenizerProfile의 역할을 명확하게 이해하고 있지 못한 상태인데 관련 document가 없는 것 같아서요, 혹시 간단하게라도 취지에 대한 설명을 부탁드릴 수 있을까요? ^^;

**Comment by MechanicKim** [comment]
@ksseono 저의 경험으로 보면 저도 이 작업을 하면서 코드를 분석해봐야 하는 경우가 생기더군요.
그러면서 테스트 코드를 추가하여 작업을 완료했는데요.

호현님이 알려주신 링크에서 OpenKoreanTextProcessor.scala를 보면
빨간 줄이 있는 부분이 있는데요.(94번째 줄)
![94](https://user-images.githubusercontent.com/12149783/27993899-219dd710-64ed-11e7-91f2-fbdce4f2dbf8.png)

위 부분이 테스트를 통과하지 못한 부분이라
이 부분을 거치는 테스트를 추가해 주셔야 합니다.

**Comment by MechanicKim** [comment]
@ksseono  혹시 이제 답이 될지는 모르겠지만...
[링크](https://coveralls.io/builds/12289012/source?filename=src%2Fmain%2Fscala%2Forg%2Fopenkoreantext%2Fprocessor%2FOpenKoreanTextProcessor.scala)

**Comment by ksseono** [comment]
@MechanicKim 감사합니다. 말씀해주신 것과 같은 테스트의 목적 자체는 이해하고 있는데요, 문제는 `TokenizerProfile`의 역할을 제대로 이해하고 있지 못하다보니, 캡쳐해주신 부분의 하이라이트된 라인에 대한 적절한 테스트코드를 작성하기 어렵다는 점입니다. 혹시 관련한 참고 내용이 있을까요?

**Comment by nlpenguin** [comment]
@ksseono 좋은 질문 감사드립니다. 그러게요 그거 documentation을 좀 할 필요가 있겠네요. Profile은 변수들을 모아놓은 일종의 configuration 파일입니다. Foursqaure에서 이 숫자들을 바꿔서 쓰고 싶다고 해서 만들었습니다. 

https://github.com/open-korean-text/open-korean-text/blob/master/src/main/scala/org/openkoreantext/processor/tokenizer/TokenizerProfile.scala

지정되지 않으면 위의 링크의 default value가 쓰이니까요 별로 신경 쓰지는 않으셔도 됩니다. 

감사합니다.

**Comment by yongfucius** [comment]
테스트 코드 작성에 초보지만 참여하고 싶습니다. 
@MechanicKim

**Comment by MechanicKim** [comment]
@yongfucius 답변이 늦어서 죄송합니다.
지금 현재 assign이 완료된 상태라서요. 혹시나 공백이 생기면 알려드리겠습니다.
감사합니다.

**Comment by MechanicKim** [comment]
Assign job to @yongfucius 
...text/processor/util/KoreanDictionaryProvider.scala - @yongfucius

**Comment by yongfucius** [comment]
https://coveralls.io/builds/12974556/source?filename=src%2Fmain%2Fscala%2Forg%2Fopenkoreantext%2Fprocessor%2Futil%2FKoreanDictionaryProvider.scala#L49

여기 보면 if 블록 안의 구문은 커버했는데, if 조건을 커버하지 못한 경우는 어떤 경우인가요?
IntelliJ coverage는 통과했는데, coveralls coverage는 통과를 못하네요. ㅠㅠ
