### ISSUE TITLE
Update examples folder

### ISSUE THREAD

**Issue by MechanicKim** [open-korean-text/open-korean-text#34]
1. examples/pom.xml
- dependency and plugin version

2. examples/src/main/java/JavaOpenKoreanTextProcessExample.java
- remove 'Stemming'

3. examples/src/main/scala/ScalaOpenKoreanTextExample.java
- remove 'Stemming'

4. Fix 'Twitter*' -> 'Open*'

**Comment by nlpenguin** [comment]
그냥 시간 난 김에 해버렸어요. @heartjigi 쏘리~!
