### ISSUE TITLE
normalizer CODA_N_EXCPETION issue

### ISSUE THREAD

**Issue by heartjigi** [open-korean-text/open-korean-text#39]
private[this] val CODA_N_EXCPETION = "은는운인텐근른픈닌든던".toSet
This exceptions cause some problems.
case ( -으, -느, -우, -이, -테, -그, -르, -프, -니, -드, -더 ) +  ㄴ + 인(데,지,가)

example
  먹인가 
 expected 먹이인가, but 먹인가.
  버근가
 expected 버그인가, but 버근가.

**Comment by MechanicKim** [comment]
About '먹인가'
'먹 + 인가' is possible. :-)

'버근' -> [http://krdic.naver.com/detail.nhn?docid=16271200](http://krdic.naver.com/detail.nhn?docid=16271200)
-.-
