### ISSUE TITLE
Stem of "몰라요"

### ISSUE THREAD

**Issue by ghostdogpr** [open-korean-text/open-korean-text#42]
I noticed that the stem we obtained for the word "몰라요" is "몰르다".
Shouldn't it be "모르다" instead?

**Comment by MechanicKim** [comment]
@ghostdogpr Yes! As far as I know, "모르다" is correct!

**Comment by nlpenguin** [comment]
붇다 -> 부다
졸르 -> 조르
일르 -> 이르
골르 -> 고르
...

**Comment by nlpenguin** [comment]
동사 활용이 맨 끝자만 건드리는데 첫글자도 건드리는 규칙을 만드는게 좋을 것 같아요. 사전에서 "몰르다" 같은 건 빼버리고.
