### ISSUE TITLE
Incorrect stem for 외로워

### ISSUE THREAD

**Issue by ghostdogpr** [open-korean-text/open-korean-text#53]
I noticed another stem issue with "외로워", it doesn't return "외롭다"as expected.

**Comment by MechanicKim** [comment]
@ghostdogpr  I tested "외로워".
<img width="665" alt="2017-08-18 1 41 40" src="https://user-images.githubusercontent.com/12149783/29444505-0140811e-841b-11e7-843a-c8278ec39d7e.png">

I confirmed that "외롭다" is included in that result.

**Comment by ghostdogpr** [comment]
You tested "외로운" but not "외로워" :)
For "외로워" it says it's a Noun.

**Comment by MechanicKim** [comment]
Oh! I got it.
I have got mistake.

**Comment by MechanicKim** [comment]
I found it!

"외로워" is in 'entities.txt' file.
The file is in noun folder. -.-
