### ISSUE TITLE
Error in loading class on ElasticSearch Plugin

### ISSUE THREAD

**Issue by ashmanmode** [open-korean-text/open-korean-text#57]
Could not initialize class org.openkoreantext.processor.tokenizer.KoreanChunker$

ES Version 2.3.4

**Comment by nlpenguin** [comment]
Thanks @ashmanmode, this should be a duplicate of https://github.com/open-korean-text/elasticsearch-analysis-openkoreantext/issues/8.

@keepcosmos, Can you help @ashmanmode here?

**Comment by ashmanmode** [comment]
Thanks @nlpenguin, I have actually written a elasticsearch(2.3.4) plugin for open-korean-text. But it is now throwing error from open-korean-text core, The exact error is as below.
{
   "error": {
      "root_cause": [
         {
            "type": "remote_transport_exception",
            "reason": "[Vengeance][127.0.0.1:9300][indices:admin/analyze[s]]"
         }
      ],
      "type": "no_class_def_found_error",
      "reason": "Could not initialize class org.openkoreantext.processor.tokenizer.KoreanChunker$"
   },
   "status": 500
}

@nlpenguin, @keepcosmos Please help me here in resolving the same.
Thanks.

**Comment by nlpenguin** [comment]
Hi @ashmanmode, as I see, it was not the plug in we provide. Can you check if you're using the right version of Scala to begin with? open-korean-text's current version is `2.12.0`.

**Comment by ashmanmode** [comment]
Yeah, right. I have actually developed a plugin, which uses open-korean-text. 
I am using scala 2.12.0

**Comment by ashmanmode** [comment]
The issue is resolved, it was twitter korean jar which was missing.
