### ISSUE TITLE
Feature Request: Ability to trigger load of resources without calling the tokenize function

### ISSUE THREAD

**Issue by ewencluley-bw** [open-korean-text/open-korean-text#64]
Open Korean Text currently loads resources lazily on first call, this is fine for a lot of applications, however for web applications can cause issues with the first request being slow (can take ~4 seconds to load the resources).  A work around is to call the tokenizer during web app start up but it would be nicer if there were a method to trigger this loading of the resources in the OpenKoreanText API.

**Comment by ewencluley-bw** [comment]
Also, this is something i am happy to implement if you guys are aligned that it maybe a useful thing to have.  If not no worries, the work around works ok.

**Comment by nlpenguin** [comment]
This is a great idea! Thank you for suggestion. Please go ahead and add it for us. I’d appreciate it a lot!

**Comment by nlpenguin** [comment]
The web code is in open-korean-text-web repo.

**Comment by nlpenguin** [comment]
Done. Please use the version 2.3.0.
