### ISSUE TITLE
토크나이징 결과 미스매치

### ISSUE THREAD

**Issue by ho9science** [open-korean-text/open-korean-text#65]
java분석예시 [한국어(Noun: 0, 3), 를(Josa: 3, 1), 처리(Noun: 5, 2), 하는(Verb(하다): 7, 2), 예시(Noun: 10, 2),
// 입니다(Adjective(이다): 12, 3), ㅋㅋㅋ(KoreanParticle: 15, 3), #한국어(Hashtag: 19, 4)]

예시를 보아도 그렇고 실제로 tokenize 결과를 보아도 그렇고
"입니다"는 "입니다(Adjective(이다): 12, 3)"로 분석되고 있습니다.

메인에 있는 예시를 보면
"입Adjective, 니다Eomi" 이렇게 분석되어야 맞는 것 같습니다.

KoreanStemmer 를 사용할 때
`nosuchelementexception : key not found` 오류가 발생합니다.

위 토크나이즈된 결과(입니다(Adjective(이다):12,3)를 인자로 사용할 때 발생됩니다.
`Seq<KoreanToken> result = stem(tokens)`

**Comment by MechanicKim** [comment]
안녕하세요. 일단 제가 찾아보니 '이다' 에 대해 견해가 많아보입니다.
https://ratsgo.github.io/korean%20linguistics/2017/06/21/ida/
토큰화의 결과가 형용사로 분류되는 것이 틀리다고 할 수 없습니다. 그렇다고 어미가 아니라고 할 수도 없습니다. 혼동의 여지가 있다면 readme를 수정해야 할 수는 있을 것 같네요.

**Comment by nlpenguin** [comment]
README 수정을 깜빡했네요. 형용사와 동사 분석이 어차피 정확하지 않고 정확할 수도 없어서 형용사/동사 + 어근의 형태로 분석하는 것으로 바꾸었습니다.
