### ISSUE TITLE
heroku application error

### ISSUE THREAD

**Issue by YOONMS** [open-korean-text/open-korean-text#74]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/14807774/43438079-66338e32-94c7-11e8-8309-0d663a138c21.png">

fix it, please.

**Comment by MechanicKim** [comment]
I'm so sorry.
API Url was changed.
https://open-korean-text-api.herokuapp.com/normalize?text=오픈코리안텍스트
You have to add '-api'.
